import "dotenv/config";
import { db } from "../db/index.js";
import {
  users,
  playerProfiles,
  consentGrants,
  invitationTokens,
  pcmeEntries,
  injuryCases,
  injuryNotes,
  trainingSessions,
} from "../shared/schema.js";

async function seed() {
  console.log("🌱 Seeding database...\n");

  // Clear existing data in reverse dependency order
  await db.delete(injuryNotes);
  await db.delete(invitationTokens);
  await db.delete(consentGrants);
  await db.delete(pcmeEntries);
  await db.delete(injuryCases);
  await db.delete(trainingSessions);
  await db.delete(playerProfiles);
  await db.delete(users);

  // ═══════════════════════════════════════════
  // ── Users (8 players + 1 doctor) ──
  // ═══════════════════════════════════════════
  await db.insert(users).values([
    {
      id: "player-james-001",
      email: "james.rodriguez@uefa.com",
      password: "password123",
      role: "player",
      phoneNumber: "+57 310 555 0101",
      onboardingComplete: true,
      nonUefa: false,
      tcAcceptedAt: new Date("2024-01-10T10:00:00Z"),
      tcSignature: "James Rodriguez",
      lastLoginAt: new Date("2024-02-20T08:30:00Z"),
    },
    {
      id: "player-ansu-002",
      email: "ansu.fati@uefa.com",
      password: "password123",
      role: "player",
      phoneNumber: "+34 612 555 0202",
      onboardingComplete: true,
      nonUefa: false,
      tcAcceptedAt: new Date("2024-01-11T10:00:00Z"),
      tcSignature: "Ansu Fati",
      lastLoginAt: new Date("2024-02-19T09:00:00Z"),
    },
    {
      id: "player-gavi-003",
      email: "gavi.paez@uefa.com",
      password: "password123",
      role: "player",
      phoneNumber: "+34 612 555 0303",
      onboardingComplete: true,
      nonUefa: false,
      tcAcceptedAt: new Date("2024-01-12T10:00:00Z"),
      tcSignature: "Gavi Páez",
      lastLoginAt: new Date("2024-02-18T11:00:00Z"),
    },
    {
      id: "player-oriol-004",
      email: "oriol.romeu@uefa.com",
      password: "password123",
      role: "player",
      phoneNumber: "+34 612 555 0404",
      onboardingComplete: true,
      nonUefa: false,
      tcAcceptedAt: new Date("2024-01-13T10:00:00Z"),
      tcSignature: "Oriol Romeu",
      lastLoginAt: new Date("2024-02-17T10:00:00Z"),
    },
    {
      id: "player-marcus-005",
      email: "marcus.miller@uefa.com",
      password: "password123",
      role: "player",
      phoneNumber: "+44 777 555 0505",
      onboardingComplete: true,
      nonUefa: false,
      tcAcceptedAt: new Date("2024-01-14T10:00:00Z"),
      tcSignature: "Marcus Miller",
      lastLoginAt: new Date("2024-02-16T10:00:00Z"),
    },
    {
      id: "player-david-006",
      email: "david.silva@uefa.com",
      password: "password123",
      role: "player",
      phoneNumber: "+34 612 555 0606",
      onboardingComplete: true,
      nonUefa: false,
      tcAcceptedAt: new Date("2024-01-15T10:00:00Z"),
      tcSignature: "David Silva",
      lastLoginAt: new Date("2024-02-15T10:00:00Z"),
    },
    {
      id: "player-alex-007",
      email: "player@uefa.com",
      password: "password123",
      role: "player",
      phoneNumber: "+34 612 345 678",
      onboardingComplete: true,
      nonUefa: false,
      tcAcceptedAt: new Date("2024-01-15T10:00:00Z"),
      tcSignature: "Alex Thompson",
      lastLoginAt: new Date("2024-02-20T08:30:00Z"),
    },
    {
      id: "player-marco-008",
      email: "marco@uefa.com",
      password: "password123",
      role: "player",
      phoneNumber: "+39 333 456 789",
      onboardingComplete: true,
      nonUefa: false,
      tcAcceptedAt: new Date("2024-01-16T10:00:00Z"),
      tcSignature: "Marco Rossi",
      lastLoginAt: new Date("2024-02-19T09:00:00Z"),
    },
    {
      id: "user-doctor-1",
      email: "doctor@uefa.com",
      password: "password123",
      role: "doctor",
      phoneNumber: "+41 79 123 4567",
      onboardingComplete: true,
      nonUefa: false,
      tcAcceptedAt: new Date("2024-01-10T10:00:00Z"),
      tcSignature: "Doctor Signature",
      lastLoginAt: new Date("2024-02-20T07:00:00Z"),
    },
  ]);
  console.log("✅ Users seeded (9)");

  // ═══════════════════════════════════════════
  // ── Player Profiles ──
  // ═══════════════════════════════════════════
  await db.insert(playerProfiles).values([
    {
      id: "profile-james",
      userId: "player-james-001",
      firstName: "James",
      lastName: "Rodriguez",
      nationality: "Colombia",
      club: "FC Barcelona",
      dob: "1991-07-12",
      position: "Midfielder",
      location: "Barcelona, Spain",
      status: "active",
      pcmeStatus: "entered",
    },
    {
      id: "profile-ansu",
      userId: "player-ansu-002",
      firstName: "Ansu",
      lastName: "Fati",
      nationality: "Spain",
      club: "FC Barcelona",
      dob: "2002-10-31",
      position: "Forward",
      location: "Barcelona, Spain",
      status: "active",
      pcmeStatus: "entered",
    },
    {
      id: "profile-gavi",
      userId: "player-gavi-003",
      firstName: "Gavi",
      lastName: "Páez",
      nationality: "Spain",
      club: "FC Barcelona",
      dob: "2004-08-05",
      position: "Midfielder",
      location: "Barcelona, Spain",
      status: "active",
      pcmeStatus: "entered",
    },
    {
      id: "profile-oriol",
      userId: "player-oriol-004",
      firstName: "Oriol",
      lastName: "Romeu",
      nationality: "Spain",
      club: "FC Barcelona",
      dob: "1991-09-24",
      position: "Midfielder",
      location: "Barcelona, Spain",
      status: "active",
      pcmeStatus: "entered",
    },
    {
      id: "profile-marcus",
      userId: "player-marcus-005",
      firstName: "Marcus",
      lastName: "Miller",
      nationality: "England",
      club: "FC Barcelona",
      dob: "1997-03-20",
      position: "Forward",
      location: "Barcelona, Spain",
      status: "active",
      pcmeStatus: "entered",
    },
    {
      id: "profile-david",
      userId: "player-david-006",
      firstName: "David",
      lastName: "Silva",
      nationality: "Spain",
      club: "FC Barcelona",
      dob: "1986-01-08",
      position: "Midfielder",
      location: "Barcelona, Spain",
      status: "active",
      pcmeStatus: "entered",
    },
    {
      id: "profile-alex",
      userId: "player-alex-007",
      firstName: "Alex",
      lastName: "Thompson",
      nationality: "England",
      club: "FC Barcelona",
      dob: "1998-03-15",
      position: "Midfielder",
      location: "Barcelona, Spain",
      status: "active",
      pcmeStatus: "entered",
    },
    {
      id: "profile-marco",
      userId: "player-marco-008",
      firstName: "Marco",
      lastName: "Rossi",
      nationality: "Italy",
      club: "AC Milan",
      dob: "1996-07-22",
      position: "Defender",
      location: "Milan, Italy",
      status: "active",
      pcmeStatus: "expected",
    },
  ]);
  console.log("✅ Player profiles seeded (8)");

  // ═══════════════════════════════════════════
  // ── Consent Grants ──
  // ═══════════════════════════════════════════
  await db.insert(consentGrants).values([
    {
      id: "consent-1",
      userId: "player-alex-007",
      granteeType: "national_team_doctor",
      granteeName: "Dr. Sarah Chen",
      granteeOrg: "FC Barcelona",
      scopes: [
        { scope: "medical_records", accessLevel: "read", duration: "permanent" },
        { scope: "injury_data", accessLevel: "edit", duration: "permanent" },
      ],
      isDefault: true,
    },
    {
      id: "consent-2",
      userId: "player-alex-007",
      granteeType: "national_team_doctor",
      granteeName: "English FA Medical",
      granteeOrg: "FA",
      scopes: [
        { scope: "medical_records", accessLevel: "read", duration: "time_bound", expiresDays: 365 },
      ],
      isDefault: false,
    },
  ]);
  console.log("✅ Consent grants seeded (2)");

  // ── Invitation Tokens ──
  await db.insert(invitationTokens).values([
    {
      id: "inv-1",
      token: "abc123token",
      consentGrantId: "consent-1",
      recipientEmail: "dr.chen@fcbarcelona.com",
      recipientName: "Dr. Sarah Chen",
      granteeOrg: "FC Barcelona",
      expiresAt: new Date("2026-12-31T23:59:59Z"),
    },
  ]);
  console.log("✅ Invitation tokens seeded (1)");

  // ═══════════════════════════════════════════
  // ── PCME Entries ──
  // ═══════════════════════════════════════════
  await db.insert(pcmeEntries).values([
    {
      id: "pcme-james",
      userId: "player-james-001",
      recordedAt: new Date("2024-01-15T09:00:00Z"),
      recordedBy: "user-doctor-1",
      bloodType: "O+",
      scatScore: 27,
      scatDate: new Date("2024-01-15"),
      ecgStatus: "normal",
      echoStatus: "normal",
      height: "180",
      weight: "75",
      asthma: "no",
      hepatitisB: "vaccinated",
      tetanusStatus: "up_to_date",
      lastVaccineDate: "2023-05-10",
      prescriptions: [],
      medicalConditions: [],
      diseases: [],
      vaccinePassport: [{ vaccine: "COVID-19 Pfizer", date: "2023-09-01", batch: "PF-2023-09" }],
      allergies: "None known",
      currentMedications: [],
      notes: "Good condition. History of calf issues — monitor closely.",
      attachments: [],
      termsAccepted: true,
      termsAcceptedAt: new Date("2024-01-15T08:50:00Z"),
      signatureData: "sig-james",
      signedAt: new Date("2024-01-15T08:50:00Z"),
    },
    {
      id: "pcme-ansu",
      userId: "player-ansu-002",
      recordedAt: new Date("2024-01-16T09:00:00Z"),
      recordedBy: "user-doctor-1",
      bloodType: "A+",
      scatScore: 29,
      scatDate: new Date("2024-01-16"),
      ecgStatus: "normal",
      echoStatus: "normal",
      height: "178",
      weight: "72",
      asthma: "no",
      hepatitisB: "vaccinated",
      tetanusStatus: "up_to_date",
      lastVaccineDate: "2023-06-20",
      prescriptions: [],
      medicalConditions: [{ condition: "Previous knee surgery", notes: "ACL reconstruction 2022", recordedAt: "2022-11-01" }],
      diseases: [],
      vaccinePassport: [{ vaccine: "COVID-19 Moderna", date: "2023-10-15", batch: "MD-2023-10" }],
      allergies: "None known",
      currentMedications: [],
      notes: "Knee rehab complete. Cleared for full activity.",
      attachments: [],
      termsAccepted: true,
      termsAcceptedAt: new Date("2024-01-16T08:50:00Z"),
      signatureData: "sig-ansu",
      signedAt: new Date("2024-01-16T08:50:00Z"),
    },
    {
      id: "pcme-gavi",
      userId: "player-gavi-003",
      recordedAt: new Date("2024-01-17T09:00:00Z"),
      recordedBy: "user-doctor-1",
      bloodType: "B+",
      scatScore: 30,
      scatDate: new Date("2024-01-17"),
      ecgStatus: "normal",
      echoStatus: "normal",
      height: "173",
      weight: "68",
      asthma: "no",
      hepatitisB: "vaccinated",
      tetanusStatus: "up_to_date",
      lastVaccineDate: "2023-07-15",
      prescriptions: [],
      medicalConditions: [],
      diseases: [],
      vaccinePassport: [{ vaccine: "COVID-19 Pfizer", date: "2023-08-01", batch: "PF-2023-08" }],
      allergies: "None known",
      currentMedications: [],
      notes: "Excellent physical condition.",
      attachments: [],
      termsAccepted: true,
      termsAcceptedAt: new Date("2024-01-17T08:50:00Z"),
      signatureData: "sig-gavi",
      signedAt: new Date("2024-01-17T08:50:00Z"),
    },
    {
      id: "pcme-oriol",
      userId: "player-oriol-004",
      recordedAt: new Date("2024-01-18T09:00:00Z"),
      recordedBy: "user-doctor-1",
      bloodType: "A-",
      scatScore: 26,
      scatDate: new Date("2024-01-18"),
      ecgStatus: "normal",
      echoStatus: "normal",
      height: "183",
      weight: "80",
      asthma: "no",
      hepatitisB: "vaccinated",
      tetanusStatus: "up_to_date",
      lastVaccineDate: "2023-04-10",
      prescriptions: [],
      medicalConditions: [],
      diseases: [],
      vaccinePassport: [{ vaccine: "Tetanus", date: "2023-04-10", batch: "TT-2023-04" }],
      allergies: "Penicillin",
      currentMedications: [],
      notes: "Veteran player. Monitor knee and back.",
      attachments: [],
      termsAccepted: true,
      termsAcceptedAt: new Date("2024-01-18T08:50:00Z"),
      signatureData: "sig-oriol",
      signedAt: new Date("2024-01-18T08:50:00Z"),
    },
    {
      id: "pcme-marcus",
      userId: "player-marcus-005",
      recordedAt: new Date("2024-01-19T09:00:00Z"),
      recordedBy: "user-doctor-1",
      bloodType: "O-",
      scatScore: 28,
      scatDate: new Date("2024-01-19"),
      ecgStatus: "normal",
      echoStatus: "normal",
      height: "185",
      weight: "78",
      asthma: "no",
      hepatitisB: "vaccinated",
      tetanusStatus: "up_to_date",
      lastVaccineDate: "2023-08-20",
      prescriptions: [],
      medicalConditions: [],
      diseases: [],
      vaccinePassport: [{ vaccine: "COVID-19 Pfizer", date: "2023-09-15", batch: "PF-2023-09B" }],
      allergies: "None known",
      currentMedications: [],
      notes: "Fast recovery profile. Prone to hamstring issues.",
      attachments: [],
      termsAccepted: true,
      termsAcceptedAt: new Date("2024-01-19T08:50:00Z"),
      signatureData: "sig-marcus",
      signedAt: new Date("2024-01-19T08:50:00Z"),
    },
    {
      id: "pcme-david",
      userId: "player-david-006",
      recordedAt: new Date("2024-01-20T09:00:00Z"),
      recordedBy: "user-doctor-1",
      bloodType: "AB+",
      scatScore: 25,
      scatDate: new Date("2024-01-20"),
      ecgStatus: "normal",
      echoStatus: "normal",
      height: "170",
      weight: "67",
      asthma: "no",
      hepatitisB: "vaccinated",
      tetanusStatus: "up_to_date",
      lastVaccineDate: "2023-06-01",
      prescriptions: [],
      medicalConditions: [],
      diseases: [],
      vaccinePassport: [{ vaccine: "COVID-19 Moderna", date: "2023-10-01", batch: "MD-2023-10B" }],
      allergies: "None known",
      currentMedications: [],
      notes: "Senior player. Excellent fitness for age.",
      attachments: [],
      termsAccepted: true,
      termsAcceptedAt: new Date("2024-01-20T08:50:00Z"),
      signatureData: "sig-david",
      signedAt: new Date("2024-01-20T08:50:00Z"),
    },
    {
      id: "pcme-alex",
      userId: "player-alex-007",
      recordedAt: new Date("2024-01-20T10:00:00Z"),
      recordedBy: "user-doctor-1",
      bloodType: "A+",
      scatScore: 28,
      scatDate: new Date("2024-01-20"),
      ecgStatus: "normal",
      echoStatus: "normal",
      height: "181",
      weight: "76",
      asthma: "no",
      hepatitisB: "vaccinated",
      tetanusStatus: "up_to_date",
      lastVaccineDate: "2023-06-15",
      prescriptions: [
        { name: "Ibuprofen", dosage: "400mg", frequency: "as needed", prescribedBy: "Dr. Chen" },
      ],
      medicalConditions: [
        { condition: "Mild astigmatism", notes: "Corrective lenses for daily use", recordedAt: "2023-01-10" },
      ],
      diseases: [],
      vaccinePassport: [
        { vaccine: "COVID-19 Pfizer", date: "2023-09-01", batch: "PF-2023-09" },
        { vaccine: "Tetanus", date: "2023-06-15", batch: "TT-2023-06" },
      ],
      allergies: "None known",
      currentMedications: [],
      notes: "Player in excellent physical condition. Cleared for full training.",
      attachments: [],
      termsAccepted: true,
      termsAcceptedAt: new Date("2024-01-20T09:55:00Z"),
      signatureData: "sig-alex",
      signedAt: new Date("2024-01-20T09:55:00Z"),
    },
    {
      id: "pcme-marco",
      userId: "player-marco-008",
      recordedAt: new Date("2024-02-01T10:00:00Z"),
      recordedBy: "user-doctor-1",
      bloodType: "O+",
      scatScore: 30,
      scatDate: new Date("2024-02-01"),
      ecgStatus: "normal",
      echoStatus: "normal",
      height: "185",
      weight: "82",
      asthma: "no",
      hepatitisB: "vaccinated",
      tetanusStatus: "up_to_date",
      lastVaccineDate: "2023-08-20",
      prescriptions: [],
      medicalConditions: [],
      diseases: [],
      vaccinePassport: [{ vaccine: "COVID-19 Moderna", date: "2023-10-15", batch: "MD-2023-10" }],
      allergies: "Penicillin",
      currentMedications: [],
      notes: "Fit to play. Monitor knee post-recovery.",
      attachments: [],
      termsAccepted: true,
      termsAcceptedAt: new Date("2024-02-01T09:50:00Z"),
      signatureData: "sig-marco",
      signedAt: new Date("2024-02-01T09:50:00Z"),
    },
  ]);
  console.log("✅ PCME entries seeded (8)");

  // ═══════════════════════════════════════════
  // ── Injury Cases (matching Replit data) ──
  // ═══════════════════════════════════════════
  await db.insert(injuryCases).values([
    // James Rodriguez — Chest/Thigh injury (Ahead)
    {
      id: "injury-james-1",
      userId: "player-james-001",
      injuryCategory: "Muscle",
      injurySubcategory: "Contusion",
      bodyArea: "Chest, Thigh",
      injuryType: "Muscle Contusion",
      mechanism: "Collision during match",
      isReinjury: false,
      severity: "moderate",
      injuryDate: "2024-01-20",
      estimatedReturnDate: "2024-02-15",
      treatmentPlan: "Rest, anti-inflammatory, gradual return",
      status: "open",
      rtpStatus: "full_training",
      createdBy: "doctor",
      notes: "Chest and thigh contusion from aerial challenge",
    },
    // James Rodriguez — Back injury (Ahead)
    {
      id: "injury-james-2",
      userId: "player-james-001",
      injuryCategory: "Muscle",
      injurySubcategory: "Strain",
      bodyArea: "Back",
      injuryType: "Lower Back Strain",
      mechanism: "Twisting motion during training",
      isReinjury: false,
      severity: "minor",
      injuryDate: "2024-02-01",
      estimatedReturnDate: "2024-02-20",
      treatmentPlan: "Physiotherapy, core strengthening",
      status: "open",
      rtpStatus: "full_training",
      createdBy: "doctor",
      notes: "Lower back strain, responding well to treatment",
    },
    // Ansu Fati — Knee injury (Ahead)
    {
      id: "injury-ansu-1",
      userId: "player-ansu-002",
      injuryCategory: "Ligament",
      injurySubcategory: "Sprain",
      bodyArea: "Knee",
      injuryType: "Knee Sprain",
      mechanism: "Landing awkwardly",
      isReinjury: false,
      severity: "moderate",
      injuryDate: "2024-01-25",
      estimatedReturnDate: "2024-03-01",
      treatmentPlan: "Brace, physiotherapy, progressive loading",
      status: "open",
      rtpStatus: "full_training",
      createdBy: "doctor",
      notes: "Knee sprain, good progress in rehab",
    },
    // Gavi Páez — Quadriceps injury (Ahead)
    {
      id: "injury-gavi-1",
      userId: "player-gavi-003",
      injuryCategory: "Muscle",
      injurySubcategory: "Strain",
      bodyArea: "Quadriceps",
      injuryType: "Quad Strain",
      mechanism: "Shooting during training",
      isReinjury: false,
      severity: "minor",
      injuryDate: "2024-02-05",
      estimatedReturnDate: "2024-02-25",
      treatmentPlan: "Rest, stretching, gradual return",
      status: "open",
      rtpStatus: "full_training",
      createdBy: "doctor",
      notes: "Minor quad strain, ahead of schedule",
    },
    // Oriol Romeu — Knee injury (Ahead)
    {
      id: "injury-oriol-1",
      userId: "player-oriol-004",
      injuryCategory: "Joint",
      injurySubcategory: "Inflammation",
      bodyArea: "Knee",
      injuryType: "Knee Inflammation",
      mechanism: "Overuse",
      isReinjury: true,
      severity: "moderate",
      injuryDate: "2024-01-30",
      estimatedReturnDate: "2024-03-05",
      treatmentPlan: "Anti-inflammatory, reduced load, physio",
      status: "open",
      rtpStatus: "full_training",
      createdBy: "doctor",
      notes: "Recurring knee inflammation, managed with reduced load",
    },
    // Marcus Miller — Hamstring injury (On Track)
    {
      id: "injury-marcus-1",
      userId: "player-marcus-005",
      injuryCategory: "Muscle",
      injurySubcategory: "Strain",
      bodyArea: "Hamstring",
      injuryType: "Grade 1 Hamstring Strain",
      mechanism: "Sprinting",
      isReinjury: false,
      severity: "minor",
      injuryDate: "2024-02-08",
      estimatedReturnDate: "2024-03-01",
      treatmentPlan: "Rest, physiotherapy, progressive running",
      status: "open",
      rtpStatus: "light_training",
      createdBy: "doctor",
      notes: "Hamstring strain, progressing well",
    },
    // Marcus Miller — Ankle injury (On Track)
    {
      id: "injury-marcus-2",
      userId: "player-marcus-005",
      injuryCategory: "Joint",
      injurySubcategory: "Sprain",
      bodyArea: "Ankle",
      injuryType: "Ankle Sprain",
      mechanism: "Tackle in match",
      isReinjury: false,
      severity: "minor",
      injuryDate: "2024-01-15",
      estimatedReturnDate: "2024-02-10",
      treatmentPlan: "RICE, ankle brace, balance training",
      status: "open",
      rtpStatus: "light_training",
      createdBy: "doctor",
      notes: "Ankle sprain, on track for return",
    },
    // David Silva — Calf injury (Behind)
    {
      id: "injury-david-1",
      userId: "player-david-006",
      injuryCategory: "Muscle",
      injurySubcategory: "Strain",
      bodyArea: "Calf",
      injuryType: "Calf Strain",
      mechanism: "Sprinting during match",
      isReinjury: true,
      severity: "moderate",
      injuryDate: "2024-01-22",
      estimatedReturnDate: "2024-03-15",
      treatmentPlan: "Extended rest, progressive loading, eccentric exercises",
      status: "open",
      rtpStatus: "in_rehab",
      createdBy: "doctor",
      notes: "Recurring calf strain. Behind schedule, needs more rehab time.",
    },
    // James Rodriguez — Ankle injury (Behind)
    {
      id: "injury-james-3",
      userId: "player-james-001",
      injuryCategory: "Joint",
      injurySubcategory: "Sprain",
      bodyArea: "Ankle",
      injuryType: "Ankle Sprain",
      mechanism: "Stepped on opponent's foot",
      isReinjury: false,
      severity: "moderate",
      injuryDate: "2024-02-12",
      estimatedReturnDate: "2024-03-20",
      treatmentPlan: "RICE, ankle support, balance work",
      status: "open",
      rtpStatus: "in_rehab",
      createdBy: "doctor",
      notes: "Ankle sprain, behind expected timeline",
    },
    // Alex Thompson — Ankle injury (Behind)
    {
      id: "injury-alex-1",
      userId: "player-alex-007",
      injuryCategory: "Joint",
      injurySubcategory: "Sprain",
      bodyArea: "Ankle",
      injuryType: "Lateral Ankle Sprain",
      mechanism: "Tackle in match",
      isReinjury: false,
      severity: "moderate",
      injuryDate: "2024-02-05",
      estimatedReturnDate: "2024-03-10",
      treatmentPlan: "RICE protocol, ankle brace, physio",
      status: "open",
      rtpStatus: "in_rehab",
      createdBy: "doctor",
      notes: "Behind schedule on recovery",
    },
    // Alex Thompson — Thigh injury (Behind)
    {
      id: "injury-alex-2",
      userId: "player-alex-007",
      injuryCategory: "Muscle",
      injurySubcategory: "Strain",
      bodyArea: "Thigh",
      injuryType: "Thigh Strain",
      mechanism: "Sprinting during training",
      isReinjury: false,
      severity: "moderate",
      injuryDate: "2024-01-10",
      estimatedReturnDate: "2024-02-15",
      treatmentPlan: "Rest, physiotherapy, gradual return",
      status: "open",
      rtpStatus: "in_rehab",
      createdBy: "player",
      notes: "Thigh strain, progressing slower than expected",
    },
  ]);
  console.log("✅ Injury cases seeded (11)");

  // ═══════════════════════════════════════════
  // ── Injury Notes ──
  // ═══════════════════════════════════════════
  await db.insert(injuryNotes).values([
    {
      id: "note-james-1",
      injuryCaseId: "injury-james-1",
      authorId: "user-doctor-1",
      intensity: 4,
      soapNotes: "S: Player reports reduced chest pain. O: Bruising subsiding. A: Contusion healing well. P: Continue gradual return to full training.",
      rtpStatus: "full_training",
      estimatedReturnDate: "2024-02-15",
      attachments: [],
    },
    {
      id: "note-ansu-1",
      injuryCaseId: "injury-ansu-1",
      authorId: "user-doctor-1",
      intensity: 5,
      soapNotes: "S: Player reports improved stability. O: Good ROM, no swelling. A: Knee sprain recovering well. P: Progress to full training drills.",
      rtpStatus: "full_training",
      estimatedReturnDate: "2024-03-01",
      attachments: [],
    },
    {
      id: "note-marcus-1",
      injuryCaseId: "injury-marcus-1",
      authorId: "user-doctor-1",
      intensity: 5,
      soapNotes: "S: Mild tightness during jogging. O: No pain on palpation, good flexibility. A: Grade 1 strain, on track. P: Light training, avoid sprints.",
      rtpStatus: "light_training",
      estimatedReturnDate: "2024-03-01",
      attachments: [],
    },
    {
      id: "note-david-1",
      injuryCaseId: "injury-david-1",
      authorId: "user-doctor-1",
      intensity: 7,
      soapNotes: "S: Player reports continued tightness in calf. O: Tenderness on palpation, limited dorsiflexion. A: Recurring calf strain, behind schedule. P: Extended rehab, eccentric loading program.",
      rtpStatus: "in_rehab",
      estimatedReturnDate: "2024-03-15",
      attachments: [],
    },
    {
      id: "note-alex-1",
      injuryCaseId: "injury-alex-1",
      authorId: "user-doctor-1",
      intensity: 6,
      soapNotes: "S: Ankle still swollen. O: Limited ROM, pain on inversion. A: Lateral ankle sprain, behind expected timeline. P: Continue RICE, physio sessions.",
      rtpStatus: "in_rehab",
      estimatedReturnDate: "2024-03-10",
      attachments: [],
    },
  ]);
  console.log("✅ Injury notes seeded (5)");

  // ═══════════════════════════════════════════
  // ── Training Sessions ──
  // ═══════════════════════════════════════════
  await db.insert(trainingSessions).values([
    {
      id: "training-1",
      date: "2024-02-20",
      type: "practice",
      title: "Match Preparation - Formation Drills",
      duration: 90,
      attendees: 22,
      notes: "Focus on defensive shape and transitions",
      timeOfDay: "morning",
      pitch: "Main Training Ground",
      distance: 8500,
    },
    {
      id: "training-2",
      date: "2024-02-19",
      type: "conditioning",
      title: "Fitness & Conditioning",
      duration: 75,
      attendees: 24,
      notes: "High-intensity interval training",
      timeOfDay: "morning",
      pitch: "Fitness Center",
      distance: 6200,
    },
    {
      id: "training-3",
      date: "2024-02-18",
      type: "recovery",
      title: "Recovery Session",
      duration: 45,
      attendees: 20,
      notes: "Light jog, stretching, pool recovery",
      timeOfDay: "afternoon",
      pitch: "Recovery Center",
      distance: 2000,
    },
    {
      id: "training-4",
      date: "2024-02-17",
      type: "practice",
      title: "Tactical Session - Pressing Patterns",
      duration: 80,
      attendees: 21,
      notes: "High press triggers and defensive transitions",
      timeOfDay: "morning",
      pitch: "Training Pitch 2",
      distance: 7200,
    },
    {
      id: "training-5",
      date: "2024-02-16",
      type: "weights",
      title: "Strength & Power",
      duration: 60,
      attendees: 18,
      notes: "Upper body and core strength focus",
      timeOfDay: "afternoon",
      pitch: "Gym",
      distance: 0,
    },
  ]);
  console.log("✅ Training sessions seeded (5)");

  console.log("\n🎉 Database seeded successfully!\n");
  process.exit(0);
}

seed().catch((err) => {
  console.error("❌ Seed failed:", err);
  process.exit(1);
});
